'use client'

import { useEffect, useRef, useState } from 'react'
import { AnimatePresence, motion, useReducedMotion } from 'motion/react'
import { FileSearch, LoaderCircle, RefreshCw, X } from 'lucide-react'
import { useReasoningTrace, usePrefetchTrace } from '@/lib/queries'
import { traceSections } from '@/lib/view-models'

type Props = { recordId?: string; open?: boolean; onOpenChange?: (open: boolean) => void }
export function TraceDrawer({ recordId = '', open: controlledOpen, onOpenChange }: Props) {
 const [localOpen,setLocalOpen]=useState(false); const [localRecordId,setLocalRecordId]=useState(recordId); const open=controlledOpen ?? localOpen; const id=recordId || localRecordId; const trace=useReasoningTrace(id,open&&Boolean(id)); const prefetch=usePrefetchTrace(); const closeRef=useRef<HTMLButtonElement>(null); const triggerRef=useRef<HTMLButtonElement>(null); const reduced=useReducedMotion(); const setOpen=(next:boolean)=>{setLocalOpen(next);onOpenChange?.(next)}
 useEffect(()=>{if(!open)return;const previous=document.activeElement as HTMLElement|null;const onKey=(event:KeyboardEvent)=>{if(event.key==='Escape')setOpen(false);if(event.key==='Tab'){const focusable=Array.from(document.querySelectorAll<HTMLElement>('.trace-drawer button, .trace-drawer input')).filter(x=>!x.hasAttribute('disabled'));if(focusable.length&&(event.shiftKey?document.activeElement===focusable[0]:document.activeElement===focusable.at(-1))){event.preventDefault();(event.shiftKey?focusable.at(-1):focusable[0])?.focus()}}};requestAnimationFrame(()=>closeRef.current?.focus());document.addEventListener('keydown',onKey);return()=>{document.removeEventListener('keydown',onKey);requestAnimationFrame(()=>triggerRef.current?.focus() || previous?.focus())}},[open])
 useEffect(()=>{if(open&&id)window.history.replaceState(null,'',`${window.location.pathname}?trace=${encodeURIComponent(id)}`)},[open,id])
 const trigger=<button ref={triggerRef} className="trace-open" onMouseEnter={()=>id&&prefetch(id)} onFocus={()=>id&&prefetch(id)} onClick={()=>setOpen(true)} aria-haspopup="dialog"><FileSearch data-icon="inline-start"/> {id?'Inspect trace':'Open backend trace'}</button>
 const sections=trace.data?traceSections(trace.data):null
 return <><span className="trace-trigger">{trigger}</span><AnimatePresence>{open&&<motion.div className="trace-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setOpen(false)}} initial={reduced?false:{opacity:0}} animate={{opacity:1}} exit={reduced?undefined:{opacity:0}}><motion.aside className="trace-drawer liquid-focal" role="dialog" aria-modal="true" aria-labelledby="trace-title" initial={reduced?false:{x:'100%'}} animate={{x:0}} exit={reduced?undefined:{x:'100%'}}><button ref={closeRef} className="trace-close" onClick={()=>setOpen(false)} aria-label="Close reasoning trace"><X/></button><span className="eyebrow">PROPOSER / VERIFIER</span><h2 id="trace-title">Reasoning trace</h2><label htmlFor="record-id">Backend record ID</label><input id="record-id" value={localRecordId} onChange={event=>setLocalRecordId(event.target.value)} placeholder="Paste a record id" autoComplete="off"/><p className="trace-hint">Evidence loaded from the FastAPI reasoning-trace endpoint.</p>{trace.isFetching&&<p aria-live="polite"><LoaderCircle className="spin"/> Loading trace…</p>}{trace.error&&<div className="run-message" role="alert">{trace.error.message}<button className="trace-open" onClick={()=>trace.refetch()}><RefreshCw/> Retry</button></div>}{sections&&<div className="trace-evidence"><EvidenceBlock title="PROPOSER" rows={sections.proposer}/><EvidenceBlock title="VERIFIER" rows={sections.verifier}/><EvidenceBlock title="FINAL DECISION" rows={sections.decision}/><EvidenceBlock title="TIMING" rows={sections.timing}/></div>}</motion.aside></motion.div>}</AnimatePresence></>
}
function EvidenceBlock({title,rows}:{title:string;rows:{label:string;value:string}[]}){return <section className="trace-block"><h3>{title}</h3>{rows.length?<div className="evidence-list">{rows.map(row=><div key={`${row.label}-${row.value}`}><span>{row.label}</span><b>{row.value}</b></div>)}</div>:<p className="muted">Not returned by backend.</p>}</section>}
