/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Run */
        post: operations["start_run_api_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Status */
        get: operations["get_status_api_status__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/results/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Latest Results
         * @description Return the newest persisted reconciliation result.
         */
        get: operations["get_latest_results_api_results_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Results
         * @description Return compact summaries for every durable run, newest first.
         */
        get: operations["list_results_api_results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/results/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Results
         * @description Return a result from live memory or durable persisted files.
         */
        get: operations["get_results_api_results__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reasoning-trace/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Reasoning Trace */
        get: operations["get_reasoning_trace_api_reasoning_trace__record_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exceptions/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Exceptions */
        get: operations["get_exceptions_api_exceptions__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ExceptionRecord */
        ExceptionRecord: {
            /** Record Id */
            record_id: string;
            /**
             * Stage
             * @description fast_path | agent_resolution | circuit_breaker
             */
            stage: string;
            /** Reason */
            reason: string;
            /** Provider */
            provider?: string | null;
            /** Detail */
            detail?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ReasoningTraceResponse */
        ReasoningTraceResponse: {
            /** Record Id */
            record_id: string;
            /** Handled By Key */
            handled_by_key?: string | null;
            /** Provider */
            provider?: string | null;
            /** History */
            history?: {
                [key: string]: unknown;
            }[];
            /** Final Status */
            final_status?: string | null;
            /** Final Decision */
            final_decision?: {
                [key: string]: unknown;
            } | null;
            /** Wall Clock Time Sec */
            wall_clock_time_sec?: number | null;
            /** Active Processing Time Sec */
            active_processing_time_sec?: number | null;
            /** Reactive Throttle Wait Sec */
            reactive_throttle_wait_sec?: number | null;
            /** Self Paced Wait Sec */
            self_paced_wait_sec?: number | null;
            /** Other Pacing Wait Sec */
            other_pacing_wait_sec?: number | null;
        };
        /** RunExceptionsResponse */
        RunExceptionsResponse: {
            /** Run Id */
            run_id: string;
            /** Exceptions */
            exceptions: components["schemas"]["ExceptionRecord"][];
            /** Dead Letter Queue */
            dead_letter_queue: components["schemas"]["ExceptionRecord"][];
        };
        /** RunResultsResponse */
        RunResultsResponse: {
            /** Run Id */
            run_id?: string | null;
            /** Run Started At */
            run_started_at: string;
            /** Timestamp */
            timestamp: string;
            /** Provider Mode */
            provider_mode: string;
            /** Total Records */
            total_records: number;
            /** Overall Match Rate */
            overall_match_rate?: number | null;
            /** Breakdown */
            breakdown: {
                [key: string]: number;
            };
            /** Full Pipeline Scores */
            full_pipeline_scores: {
                [key: string]: unknown;
            };
            /** Baseline Scores */
            baseline_scores: {
                [key: string]: unknown;
            };
            /** Performance */
            performance: {
                [key: string]: unknown;
            };
            /** Ground Truth Orphan Rows Excluded */
            ground_truth_orphan_rows_excluded: number;
            /** Dead Letter Queue */
            dead_letter_queue?: {
                [key: string]: unknown;
            }[];
            /** Caveats */
            caveats?: string[];
        };
        /**
         * RunResultsSummary
         * @description Compact durable run record used by the dashboard archive.
         */
        RunResultsSummary: {
            /** Run Id */
            run_id?: string | null;
            /** Run Started At */
            run_started_at?: string | null;
            /** Timestamp */
            timestamp?: string | null;
            /** Provider Mode */
            provider_mode?: string | null;
            /** Total Records */
            total_records?: number | null;
            /** Overall Match Rate */
            overall_match_rate?: number | null;
            /** Breakdown */
            breakdown?: {
                [key: string]: number;
            };
        };
        /** RunStartResponse */
        RunStartResponse: {
            /** Run Id */
            run_id: string;
            /** Status */
            status: string;
            /** Provider Mode */
            provider_mode: string;
        };
        /** RunStatusResponse */
        RunStatusResponse: {
            /**
             * Status
             * @description pending | running | completed | failed
             */
            status: string;
            /** Records Processed */
            records_processed: number;
            /** Total Records */
            total_records: number;
            /** Fast Path Resolved So Far */
            fast_path_resolved_so_far: number;
            /** Agent Resolved So Far */
            agent_resolved_so_far: number;
            /** Error */
            error?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    start_run_api_run_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_status_api_status__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_latest_results_api_results_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResultsResponse"];
                };
            };
        };
    };
    list_results_api_results_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResultsSummary"][];
                };
            };
        };
    };
    get_results_api_results__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResultsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_reasoning_trace_api_reasoning_trace__record_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReasoningTraceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exceptions_api_exceptions__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunExceptionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
